### ISSUE TITLE
Images from restricted channels

### ISSUE THREAD

**Issue by balki97** [khoben/telemirror#44]
As I've been using telemirror for a while now and came to test all of its features. I can confirm that it pulls content from restricted channels but just not media (images,videos). I just want to confirm if this is a problem from my side or its something that cannot be achieved ?

**Comment by khoben** [comment]
> As I've been using telemirror for a while now and came to test all of its features. I can confirm that it pulls content from restricted channels but just not media (images,videos). I just want to confirm if this is a problem from my side or its something that cannot be achieved ?

You can only retrieve and forward content from protected channels by re-saving it. The easiest ones are text and images. Text is simply copied and images are downloaded as an array of bytes and sent. The other types of media require a bit more processing logic.
I have now completely removed option to forward from such channels, but this is easily fixed by removing checks for the `noforwards` chat flag and implementing re-saving.

For forwarding text and pictures, you can do the following:
1. Check that `chat` has the `noforwards` flag
2. If the `incomin_message.media` is a picture, download it as an array of bytes (or even to storage) and re-send it:
```
downloaded_bytes = await self.download_media(incoming_message, file=bytes)
self.send_message(
                  entity=outgoing_chat,
                  message=incoming_message.message,
                  file=downloaded_bytes,
                  formatting_entities=incoming_message.entities,
                  reply_to=reply_to_messages.get(outgoing_chat)
)
```
Such a scheme worked quite well. To handle more media types, you should use storage and check if it makes sense to reload large files.
